# Generated by Django 4.2 on 2024-11-20 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Наименование заказчика')),
                ('adress', models.CharField(max_length=120, verbose_name='Адрес заказчика')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер машины')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Наименование товара')),
                ('price', models.BooleanField(max_length=120, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=12, verbose_name='Номер договора')),
                ('date_contract', models.DateField(blank=True, null=True)),
                ('shipment', models.BooleanField(max_length=120, verbose_name='Поставка')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_customer', to='myapp.customer', verbose_name='Заказчик')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_product', to='myapp.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_shipment', models.DateField(blank=True, null=True)),
                ('dispatch_count', models.IntegerField()),
                ('id_orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_orders', to='myapp.orders', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Отгрузка',
                'verbose_name_plural': 'Отгрузки',
                'ordering': ['id'],
            },
        ),
    ]
