# Generated by Django 4.2 on 2024-11-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_count',
            field=models.CharField(max_length=120, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipment',
            field=models.CharField(max_length=120, verbose_name='Поставка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
